### ISSUE TITLE
Failed prop type

### ISSUE THREAD

**Issue by elmondino** [souporserious/react-measure#46] opened 2017-04-21 10:21 UTC
I'm seeing this issue. 

Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types
    in Measure (created by List)

I'm using     
"react": "^15.5.4" 
"react-dom": "^15.5.4" 
  "react-measure": "^1.4.7"

**Comment by souporserious** [comment] 2017-04-26 18:17
Can you post what your code looks like please? I'm not sure what would be throwing that error 🤔

**Comment by gaearon** [comment] 2017-05-12 14:54
Please see https://github.com/reactjs/prop-types/issues/38.

This was a false positive caused by production version of `prop-types` generating a mistaken warning when development version of React is calling it.

**It is fixed in `prop-types@15.5.10`.**

You might need to rebuild the UMD bundle of the component that depends on `prop-types` (probably this repo) to see the changes.

**Comment by souporserious** [comment] 2017-05-12 17:11
Thanks @gaearon 😄  I'll upgrade ASAP.

**Comment by souporserious** [comment] 2017-05-30 10:00
The `prop-types` package has been upgraded in the latest release :)

**Closed as completed by souporserious** 2017-05-30 10:00 UTC
