### ISSUE TITLE
Scrollbar triggers odd alternating resize issue

### ISSUE THREAD

**Issue by Nosherwan** [souporserious/react-measure#31] opened 2017-01-23 01:16 UTC
I am using react-measure to alternate between mobile and desktop views, however for mobile view I have to restrict the height of the container div. Doing so is causing a odd behaviour where once the scroll bar is introduced react-measure starts alternating between two widths values that are being returned. This happens for 15px in-between the upper and lower bound of a particular width value, based on the mobile width defined. Is there a way to disregard the scrollbar width or any other solution to this issue?

**Comment by souporserious** [comment] 2017-01-23 15:34
Hmm interesting. It sounds like a circularity issue like described [here](https://au.si/css-container-queries#the-recursion-issue). You might be able to get the scrollbar width like you said and account for that in your measurement to fix the issue.

Is it possible you can provide a reduced test case showing your issue? You can fork this [Codepen](http://codepen.io/souporserious/pen/rLdwao/) to get a good base started if you want. That would help me tremendously so I can get an idea of what's going on :)

**Comment by Nosherwan** [comment] 2017-01-23 23:01
Thanks @souporserious for the quick response and keen interest.
I have read the circularity issue that you have pointed at unfortunately I am not sure if that is the case here.
However I have used your Codepen and forked it and have created the odd behaviour.
Here is my [CodePen](http://codepen.io/nosherwan/pen/egREMp).
If you resize the window by contracting at about 400 to 415px you can see the alternating behaviour.
Let us know your thoughts.

**Comment by souporserious** [comment] 2017-01-24 21:13
Thank you for the pen! :) However, I'm not seeing the issue you describe. I'm guessing and hoping it's another browser so I can reproduce. I'm on Chrome 55.0.2883.95. What browser and what version are seeing the issue in?

**Comment by Nosherwan** [comment] 2017-01-24 21:44
It is happening on both chrome Version 55.0.2883.95 (64-bit) and firefox 50.1.0 . Here is a gif I have recorded to show the actual behaviour, even though the recorded gif alternates in slow speed, in actual view it happens more frequently. I have recorded for both chrome and firefox. [recorded gif](http://recordit.co/iKVHUH9kRx)

**Comment by souporserious** [comment] 2017-01-25 00:57
Ok I got it to do it! My browser height was too tall, once I shrunk it enough it started doing it. Super weird! I'll look into this when I get a chance and get back to you. I'm open to a PR if you stumble upon a solution before then.

**Comment by que-etc** [comment] 2017-02-20 17:37
@Nosherwan, @souporserious  There is no bug. This is a completely valid behavior from my point of view :)

1. The observed element receives resize notifications because it's width actually increases whenever it's parent node loses rendered scroll bars, which in this case leads to a continuous loop because of this condition: `dimensions.width < 400 ? 'mobile': 'desktop'`. So, it will be jumping back and forth between styles until the dimensions will get either smaller than `width - scrollBarWidth` or greater than `400px`.
    1. Element's width shrinks to 399px and Measure component fires notification.
    2. Element receives the 'mobile' class which removes scroll bars from the parent node.
    3. Element's dimensions take available space and it's width increases to 399px + scrollbarWidth.
    4. Measure fires notification.
    5. Element receives the 'desktop' class which adds scroll bars back to the parent.
    6. Element's width shrinks to 399px bringing us back to step 1 :)
    ...

2. I see that there is a `overflow-y` CSS property defined for the observed element, but it won't work because the Measure component calculates the border-box rectangle including the size of rendered scroll bars. I've moved this property to the parent node and it kinda does the trick: [example](http://codepen.io/que-etc/pen/OWeGmE).

**Comment by souporserious** [comment] 2017-02-20 19:50
@que-etc thanks for checking this out :) and thanks for the explanation! I'm going to close this since it sounds like the implementation is causing circularity rather than a bug.

**Closed as completed by souporserious** 2017-02-20 19:50 UTC
Labels: bug

**Comment by Nosherwan** [comment] 2017-02-20 21:31
@que-etc thank you for the explanation. 

However the component I am working on is a tab container. So the external container has fixed position tabs, while the internal component that has the `overflow-y` CSS property forms content that can be scrolled therefore it is not an option for me to move it out.

Even though this is not an actual bug and a circularity issue, any other suggestions would be appreciated.

**Comment by souporserious** [comment] 2017-02-21 03:48
Hmm maybe you can calculate the scrollbar size and account for that in your breakpoint? [Here's a way](https://github.com/davidtheclark/no-scroll/blob/master/index.js#L5-L15) to get the scrollbar width.
