### ISSUE TITLE
Issue with contentRect.bounds

### ISSUE THREAD

**Issue by sherwinski** [souporserious/react-measure#137] opened 2019-04-16 22:57 UTC
Hi, we're using react-measure to determine the size of an image we want to render. It seems that after updating to the latest release (v2.2.6), `contentRect.bounds.width` and `contentRect.bounds.height` are consistently returning 0, which prevents our component from loading.

Here is a comparison showing the component using [v2.2.6](https://codesandbox.io/s/3vv22zopj6) versus [v2.2.5](https://codesandbox.io/s/zk86221wq4). And some [additional context](https://github.com/imgix/react-imgix/blob/15b0073f7b14679ebd6c43c1cf79bfb9c64b35c2/src/react-imgix-bg.jsx#L50) on how we're using `contentRect`.

Is this intended behavior or possibly a regression introduced by changes in the last release? Any advice would be appreciated. Thanks!

**Comment by souporserious** [comment] 2019-04-16 23:31
Ah, sorry about that! It looks like a regression from [here](https://github.com/souporserious/react-measure/commit/dea8f0ce43ff9c7ae5f201a6cf43b52d816df74d) 😞. I'll work on getting a fix together. Just want to make sure you aren't relying on `onResize` and only what comes back in the child function?

**Comment by sherwinski** [comment] 2019-04-16 23:54
Thanks for quick response! And yes I believe that is correct.

**Comment by michal-murawski** [comment] 2019-04-17 08:03
I was about to post the same issue. No reaction on initial render, but the data is passed properly to `bounds` when the windows size changes. After downgrade to 2.2.4 works.

We do not use `onResize` and simply just render `<Measure>` and use `ref={measureRef}` with `contentReact` for different components

**Comment by souporserious** [comment] 2019-04-18 21:01
Should be fixed under `2.3.0` 🤞. Thanks for letting me know about the issue and please feel free to reopen if you see any similar problems.

**Closed as completed by souporserious** 2019-04-18 21:01 UTC
